export enum Strings {
  EMAIL_PLACEHOLDER = "Email",
  PASSWORD_PLACEHOLDER = "Password",
  DISPLAY_NAME_PLACEHOLDER = "Display Name",
  CREATING_ACCOUNT = "Creating Account...",
  SIGN_UP = "Sign Up",
  EMAIL_AUTH = "Email Auth",
  PHONE_AUTH = "Phone Auth",
  SIGNING_IN = "Signing In...",
  SIGN_IN = "Sign In",
  SIGN_UP_ERROR = "Sign Up Error",
  SIGN_IN_ERROR = "Sign In Error",
  SENDING = "Sending...",
  SEND = "Send",
  UNKNOWN_USER = "Unknown User",
  UNKNOWN_TIME = "Unknown Time",
  VERIFICATION_CODE = "Verification Code",
  SENDING_OTP = "Sending OTP...",
  SEND_OTP = "Send OTP",
  PHONE_NUMBER = "Phone Number",
  VERIFYING = "Verifying...",
  VERIFY_CODE = "Verify Code",
  PHONE_AUTHENTICATION = "Phone Authentication",
}
